version: '3'

services:
  bdd:
    container_name: mysqlsorties
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sorties
      MYSQL_DATABASE: sortiedb
      TZ: Europe/Paris
    expose:
      - "3306"
    ports:
      - "3309:3306"
    volumes:
      - bdd-data:/var/lib/mysql

volumes:
  ###> doctrine/doctrine-bundle ###
  bdd-data:
###< doctrine/doctrine-bundle ###
